name: 'Setup custom tool'
description: 'Download, unpack, and add to PATH a tool of your choice'
icon: 'download'
color: 'purple'
author: 'Alex079'
inputs:
  archiveUrl:
    description: 'URL to download from'
    required: true
  archiveGlob:
    description: 'Glob expression to find directory inside archive to add to path after unpacking'
    required: false
  toolName:
    description: 'Name of the tool in cache'
    required: false
  toolVersion:
    description: 'Version of the tool in cache'
    required: false
  toolArch:
    description: 'Target platform architecture of the tool in cache'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
