name: 'setup-custom-tool'
description: 'Download and unpack a tool of your choice'
author: 'Alex079'
inputs:
  toolUrl:
    description: 'URL to download from'
    required: true
  archiveGlob:
    description: 'A glob expression to find directory inside archive to add to path after unpacking'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
