name: "build"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run all
