name: CI

on:
  - pull_request
  - push

jobs:
  build:
    name: Install, build, test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        run: |
          yarn install
          yarn run all
  run:
    name: Deploy ${{matrix.ext}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ext:
          - .zip
          - .tar.gz
          - .tar.bz2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy ${{matrix.ext}}
        uses: ./
        with: 
          archiveUrl: https://github.com/Alex079/setup-custom-tool/wiki/sample/content${{matrix.ext}}
          archiveGlob: '*'
