name: "test"
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with: 
          archiveUrl: 'https://github.com/Alex079/setup-custom-tool/wiki/sample/content.zip'
          archiveGlob: '*'

